name = "PlanePolygons"
uuid = "f937978b-597e-4162-b50e-ad07b6cf7ab2"
authors = ["Sasha Fleming <fleming@stce.rwth-aachen.de> and contributors"]
version = "0.1.6"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
Mooncake = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"

[extensions]
MooncakeExt = "Mooncake"

[compat]
LinearAlgebra = "1.10"
Mooncake = "0.4"
StaticArrays = "1.9"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Mooncake = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"

[targets]
test = ["Mooncake", "Test"]
